version: "3.7"

services:
  app:
    build: .
    depends_on:
      - fulcrum
    command: npm run dev:backend
    restart: on-failure
    environment:
      ELECTRUM_HIDDEN_SERVICE: "somehiddenserviceurl.onion"
      ELECTRUM_LOCAL_SERVICE: "umbrel.local"
      FULCRUM_HOST: fulcrum
      BITCOIN_HOST: bitcoind
      RPC_USER: umbrel
      RPC_PASSWORD: moneyprintergobrrr
    ports:
      - "3006:3006"
  fulcrum:
    image: cculianu/fulcrum:v1.11.1@sha256:70f06b93ab5863997992d4b4508312fe81ce576017e16ecc7e69c7d38165bdf2
    environment:
      TCP: 0.0.0.0:50001
      ADMIN: 0.0.0.0:8000
      BITCOIND: bitcoind:18443
      RPCUSER: umbrel
      RPCPASSWORD: moneyprintergobrrr
      PEERING: "false"
      ANNOUNCE: "false"
    command: Fulcrum _ENV_
    volumes:
      - ${PWD}/data/fulcrum:/data
    restart: always
    ports:
      - "50001:50001"
  bitcoind:
    image: lncm/bitcoind:v22.0@sha256:37a1adb29b3abc9f972f0d981f45e41e5fca2e22816a023faa9fdc0084aa4507
    command: -regtest -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcauth=umbrel:5071d8b3ba93e53e414446ff9f1b7d7b$$375e9731abd2cd2c2c44d2327ec19f4f2644256fdeaf4fc5229bf98b778aafec
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin
    restart: on-failure
    ports:
      - "18443:18443"
